[package]
name = "rrr"
version = "0.1.0"
authors = ["lePerdu <zdpeltzer@gmail.com>"]
edition = "2018"

[dependencies.num-traits]
version = "0.2"
default-features = false

[features]
default = ["std"]
std = ["num-traits/std"]
